## Welcome to the blog of my personal thoughts, very personal.

```markdown
## #1 Site ismi belirlemeceler ve diğer sorunsallar.
Herkese merhaba ! Daha fazla erteleyemedim ve bu hafta sonu 21 Aralık gününe kısmet olan ilk yazımı yazmaya karar verdim😎. Hala bitmeyen işler, train edilmemiş modeller, tam tutturulmamış hedefler beklerken araya sıkıştırabileceğimi düşündüm. Şu an biraz heyecanlandığımı fark ettim küçük bir girizgah sorunuyla karşılaşabilirim diye endişelerim vardı ama hafta içileri günün çoğu zamanında yazmak istediklerimi düşündüğüm için parça parça da olsa kafamda bir şeyler oluşturmuştum. İmla kurallarına ve özelikle -de,-ki bağlaçlarının doğru yazılıp yazılmadığı ile ilgili içlerinde sürekli bir gelgit yaşayanlar için "de" özen göstermeye çalışacağım😬  

Başlıktan da anlaşılacağı üzere öncelikle neden bir site kurmak istediğimden hatta neden bedava uzantılı sitelerden değil de cüzi de olsa bir para vererek sahip olduğun alan adı almak istediğimden bahsedeyim. Efenim şimdi şöyle oldu bundan 3 ay önce kadar yaklaşık toplam 2 senelik çalışma hayatımdaki 3. tam zamanlı işten de ayrılıp yeni bir işe başlamadan hem kafamdaki sorunları çözmek hem de birazcık yeni hobiler edinmek, sadece iş odaklı yaşamayıp, task odaklı bir zihniyetten ziyade biraz olsun kendime vakit ayırıp bir şeyler yapma hatta yaptıklarımı da paylaşma isteğimden ortaya çıktı. Site ismi belirleme kısmı da nerden baksanız 1 haftamı aldı diyebilirim çünkü hali hazırda işten sonra zaten kendime ayırabildiğim zaman da sınırlı hak verirsiniz ki. He bir de kendime özel olmasını istedim yani ben de her yeri diyar diyar gezen gezgin tumblr kızı olmak isterdim tabi ki ama ne yazık ki popilik seviyem o noktalarda değil. Ama şimdi düşününce istemezdim gibi geldi, ŞS modunda takılmak da eminim kendimi kötü hissettirirdi bence. Neyse velhasıl kelam baya bir isim düşündüm, hayaller tabi ki gezgin  temalı bir site olmasıydı, bizevdeyokuz.com , birhayalinpesinde.com gibi orjinal ve içi dolu dolu yazacağım bir site kim istemez ki..

Birçok arkadaşıma ama daha çok benim gerçekten ne istediğime değer veren, düşüncelerime saygı duyan ve dürüstlüklerinden hiç şüphe duymadığımdan görüşlerine güvenebileceğim sevdiceklerime danıştım. Aslında konuyu biraz dağıttığımı ve tam çıkış noktasını veremediğimi fark ettim şu an. Yukarıda biraz kendime zaman ayırıp hobilerimden yada aklıma takılan gündelik sorunsallardan bahsetme isteyişim olduğunu söylemiştim ama en birincil sebebi kesinlikle "İŞTEN SONRA HAYATININ OLUP OLMADIĞINA İNANIP İNANMAMAKLA" ilgiliydi. Yani bi' insanın hayattaki gerçek amacı mevki, daha çok para, hayatı boyunca 30 sene sonrasında rahata ereceğim mantığıyla ev için araba için taksitler içinde yaşayıp kendini garanti altına alma anlayışı olmamalı bence (burdan 2. yazımın konusu spoiler veriyorum o halde :) ). Hoş tabi şu an çok kişisel bir noktaya değinmiş oldum amma velakin biraz düşününce gerçekten mantıklı ve bence siz de saçmalamadığımı fark edeceksiniz😄. Bu paragrafın konusu tekrardan dağıldı, özetle şu isim önerilerinden istherealifeafterwork.com,  doyoubelieveinlifeafterwork.com lardan aslihaning.com ve aslihanable.com (bu blog name generator tarafından verilen bir öneri🙂 ( evet böyle bir site de varmış  name-generator.org.uk/blog/ ) 'a gelmiş bulundum. Biraz da saçma ama eğlenceli olmasını istedim.
 Özetle şu şekilde :

"hani bence öbürüne göre daha güzel available gibi.." 
"aslihaning koşturmacaya dalmış Aslıhan gibi hissettiriyor"
"2'si de çok saçma bence biraz daha düşünüp daha iyilerini bulabilirsin.." 

farklı yorumlar aldım. .
aslihanable biraz sayko geldi kulağıma hannibal gibi😅, her ne kadar öyle bir tarafım olsa da çok aklıma yatmadı. Sonra yukarıda özellikle belirttiğim yorumu aldıktan sonra "EE BU BENİM Kİ" şeklinde bi' tebessüm belirdi yüzümde😊. İş hayatına başladıktan sonra biraz kırsam da bu özelliğimi, finallere bile geç kaldığım hatta yoğunluktan tarihini bile karıştırıp girmediğim zamanlarımı es geçemezdim be sebeple de hep bi' koşuşturmacaya dalmış olma fikrini satın aldım🏃‍♀️ 💃  
 
Eveeeet bu yazımı burada noktalıyorum, online günlükler ve diğer ekşi sözlük başlıkları tadındaki yazılarımı yazmak için hevesli ve heyecanlıyım. Bir sonraki yazım pek muhtemel yaklaşık 2 ay önce beni hayata bağlayan edindiğim bir hobim olan yüzme (başlangıçta 50m bile zor yüzen kendimin şu an nasıl 2x800 antremanlarını yapacak hale geldiğimden ve temmuzdaki kıtalar arası yüzme yarışına hazırlanma aşamasından bahsedebilirim) yada yukarıda bahsettiğim bir "beyaz yaka çıkmazı" başlıklı bir yazı olabülü. İlerleyen zamanlarda şengen'e başvurmam'la beraber yapacağım haftasonu gezilerimi de paylaşabilirim. Son olarak Spotify ile çok geç tanışmış ama çok mutlu bir birliktelik yaşamakta olduğumdan her yazımın sonuna ruh halime göre bir şarkı önerisi de eklemeye karar verdim. İyi dinlemeler 🥳  O zaman görüşürüz, çok çalışın ama hayatı kaçırmayın✌️. 

[Link](https://open.spotify.com/embed/track/3NBSDl1rEbzi9MFiXN6OnP)
```
